version = 1

exclude_patterns = [
  ".git",
  "__pycache__",
  "requirements",
  "scripts",
  "alembic"
]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"